---

services:
  unifi:
    container_name: ${container_name}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        container_uid: $uid
        container_gid: $gid
    image: local/unifi
    init: true
    restart: unless-stopped
    user: ${uid}:${gid}
    environment:
      - TZ='Europe/Berlin'
    volumes:
      - "${base_dir}:/unifi"
    networks:
      unifi:
        aliases:
          - ${container_name}
        ipv4_address: ${ipv4_address}

networks:
  unifi:
    name: ${macvlan_name}
    driver: macvlan
    driver_opts:
      parent: ${interface}
    ipam:
      config:
        - subnet: ${ipv4_network}
          ip_range: ${ipv4_address}/31
          gateway: ${ipv4_gateway}

...
