---

services:
  unifi-controller:
    container_name: unifi
    image: 'linuxserver/unifi-controller:latest'
    init: false
    privileged: false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--max-time", "5", "--head", "--location", "--fail", "--insecure", "--silent", "https://127.0.0.1:8443/"]
      interval: 30s
      timeout: 5s
      retries: 5
    stop_grace_period: 60s
    environment:
      - 'TZ=Europe/Berlin'
      - 'PUID=999'
      - 'PGID=999'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - 'data:/config/data:rw'
      - 'log:/config/log:rw'
      - 'run:/config/run:rw'
    networks:
      frontend:
        ipv4_address: 10.0.0.30

networks:
  frontend:
    name: unifi-frontend
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      config:
        - subnet: 10.0.0.0/24
          ip_range: 10.0.0.30/31
          gateway: 10.0.0.1

volumes:
  data:
    driver: local
  log:
    driver: local
  run:
    driver: local

...
