---

services:
  unifi-controller:
    container_name: unifi
    image: 'linuxserver/unifi-controller:latest'
    init: false
    privileged: false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--max-time", "5", "--head", "--location", "--fail", "--insecure", "--silent", "https://127.0.0.1:8443/"]
      interval: 30s
      timeout: 5s
      retries: 5
    stop_grace_period: 60s
    environment:
      - 'TZ=Europe/Berlin'
      - 'PUID=999'
      - 'PGID=999'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - 'data:/config/data:rw'
      - 'log:/config/log:rw'
      - 'run:/config/run:rw'
    networks:
      - frontend
    ports:
      - 0.0.0.0:8443:8443/tcp # Application GUI/API
      - 0.0.0.0:3478:3478/udp # STUN
      - 0.0.0.0:10001:10001/udp # Device discovery
      - 0.0.0.0:8080:8080/tcp # Device and application communication
      # - 1900:1900/udp # Make application discoverable on L2 network (optional)
      # - 8843:8843 # HTTPS portal redirection (optional)
      # - 8880:8880 # HTTP portal redirection (optional)
      # - 6789:6789 # UniFi mobile speed test (optional)
      # - 5514:5514/udp # Remote syslog capture (optional)

networks:
  frontend:
    name: unifi-frontend
    driver: bridge

volumes:
  data:
    driver: local
  log:
    driver: local
  run:
    driver: local

...
