---

services:
  unifi:
    container_name: unifi01
    build:
      context: .
      dockerfile: ./Dockerfile_unifi01
      args:
        container_uid: 1000
        container_gid: 1000
    init: true
    restart: unless-stopped
    user: 1000:1000
    environment:
      - TZ='Europe/Berlin'
    volumes:
      - "/usr/local/share/unifi:/unifi"
    networks:
      unifi:
        aliases:
          - unifi01
        ipv4_address: 10.0.0.30

networks:
  unifi:
    name: unifi01
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      config:
        - subnet: 10.0.0.0/24
          ip_range: 10.0.0.30/31
          gateway: 10.0.0.1

...
