services:
  omada-controller:
    container_name: omada
    image: 'mbentley/omada-controller:5.9-chromium'
    init: true
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--timeout=5", "--spider", "--no-check-certificate", "--quiet", "https://127.0.0.1:${MANAGE_HTTPS_PORT:-8043}/"]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      - 'TZ=Europe/Berlin'
      - 'PUID=508'
      - 'PGID=508'
      - 'MANAGE_HTTP_PORT=8088'
      - 'MANAGE_HTTPS_PORT=8043'
      - 'PORTAL_HTTP_PORT=8088'
      - 'PORTAL_HTTPS_PORT=8043'
      - 'PORT_APP_DISCOVERY=27001'
      - 'PORT_ADOPT_V1=29812'
      - 'PORT_UPGRADE_V1=29813'
      - 'PORT_MANAGER_V1=29811'
      - 'PORT_MANAGER_V2=29814'
      - 'PORT_DISCOVERY=29810'
      - 'SHOW_SERVER_LOGS=true'
      - 'SHOW_MONGODB_LOGS=false'
    networks:
      - omada
    ports:
      - '0.0.0.0:8088:8088/tcp'
      - '0.0.0.0:8043:8043/tcp'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - 'data:/opt/tplink/EAPController/data:rw'
      - 'logs:/opt/tplink/EAPController/logs:rw'

networks:
  omada:
    name: omada-frontend
    driver: bridge

volumes:
  data:
    driver: local
  logs:
    driver: local

