---

services:
  omada-controller:
    container_name: omada
    image: 'mbentley/omada-controller:latest-chromium'
    init: true
    privileged: false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--timeout=5", "--spider", "--no-check-certificate", "--quiet", "https://127.0.0.1:${MANAGE_HTTPS_PORT:-8043}/"]
      interval: 30s
      timeout: 5s
      retries: 5
    stop_grace_period: 60s
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    environment:
      - 'TZ=Europe/Berlin'
      - 'PUID=508'
      - 'PGID=508'
      - 'MANAGE_HTTP_PORT=8088'
      - 'MANAGE_HTTPS_PORT=8043'
      - 'PORTAL_HTTP_PORT=8088'
      - 'PORTAL_HTTPS_PORT=8843'
      - 'PORT_APP_DISCOVERY=27001'
      - 'PORT_ADOPT_V1=29812'
      - 'PORT_UPGRADE_V1=29813'
      - 'PORT_MANAGER_V1=29811'
      - 'PORT_MANAGER_V2=29814'
      - 'PORT_DISCOVERY=29810'
      - 'PORT_TRANSFER_V2=29815'
      - 'PORT_RTTY=29816'
      - 'SHOW_SERVER_LOGS=true'
      - 'SHOW_MONGODB_LOGS=false'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - 'data:/opt/tplink/EAPController/data:rw'
      - 'logs:/opt/tplink/EAPController/logs:rw'
    networks:
      - frontend
    ports:
      - '0.0.0.0:8088:8088/tcp'
      - '0.0.0.0:8043:8043/tcp'
      - '0.0.0.0:27001:27001/udp' # The Omada APP discovers whether a controller is running in the LAN since Omada Controller v4.x
      - '0.0.0.0:29810:29810/udp' # Discovers Omada devices
      - '0.0.0.0:29811:29811/tcp' # Manages Omada devices before Omada Controller v5.x
      - '0.0.0.0:29812:29812/tcp' # Manages Omada devices before Omada Controller v5.x
      - '0.0.0.0:29813:29813/tcp' # Upgrades Omada devices before Omada Controller v5.x
      - '0.0.0.0:29814:29814/tcp' # Adopts Omada devices since Omada Controller v5.x
      - '0.0.0.0:29815:29815/tcp' # Omada Controller receives Device Info and Packet Capture files from the Omada devices
      - '0.0.0.0:29816:29816/tcp' # Omada Controller establishes the remote control terminal session with the Omada devices

volumes:
  data:
    driver: local
  logs:
    driver: local

networks:
  frontend:
    name: omada-frontend
    driver: bridge

...
