---

services:
  homeassistant:
    container_name: homeassistant02
    image: "ghcr.io/home-assistant/home-assistant:stable"
    privileged: true
    user: 1000:1000
    restart: unless-stopped
    # command: [ "python", "-m", "homeassistant", "--config", "/config", "--log-rotate-days", '3' ]
    environment:
      - TZ='Europe/Berlin'
    volumes:
      - /home/northdakota/homeassistant02:/config:rw
      - /home/northdakota/homeassistant02/www:/media:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    network_mode: host

...

