---

services:
  homeassistant:
    container_name: hass01
    image: ghcr.io/home-assistant/raspberrypi4-64-homeassistant:stable
    privileged: false
    user: 1000:1000
    restart: unless-stopped
    # command: [ "python", "-m", "homeassistant", "--config", "/config", "--log-rotate-days", '3' ]
    environment:
      - TZ='Europe/Berlin'
    volumes:
      - /home/northdakota/homeassistant01:/config:rw
      - /home/northdakota/homeassistant01/www:/media:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      backend:
        ipv4_address: 172.20.0.2
    ports:
      - 8123:8123
      - 8943:8943
    depends_on:
      - mariadb

  mariadb:
    container_name: hass01-db
    image: mariadb:jammy
    privileged: false
    user: 1000:1000
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=qwertz#2022
      - TZ='Europe/Berlin'
    volumes:
      - /home/northdakota/homeassistant01_db:/var/lib/mysql
      - /home/northdakota/homeassistant01/sql:/docker-entrypoint-initdb.d
    networks:
      backend:
        ipv4_address: 172.20.0.3

networks:
  backend:
    name: hass01-backend
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/29
          gateway: 172.20.0.1

...

