---

services:
  homeassistant:
    container_name: hass
    build:
      context: .
      dockerfile_inline: |
        FROM homeassistant/home-assistant:stable
        # FROM homeassistant/raspberrypi4-homeassistant:stable
        # See: https://github.com/mitch-dc/volkswagen_we_connect_id/blob/main/custom_components/volkswagen_we_connect_id/manifest.json
        RUN pip install --root-user-action=ignore --upgrade pip && \
            pip install --root-user-action=ignore weconnect>=0.54.0 ascii_magic>=2.0.0
        RUN mkdir -p /config/.storage && \
            chown -R 1000:1000 /config/.[!.]*
        USER 1000:1000
      tags:
        - "local/homeassistant:stable"
    init: false
    privileged: false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--timeout=5", "--spider", "--no-check-certificate", "--quiet", "http://127.0.0.1:8123/"]
      interval: 30s
      timeout: 5s
      retries: 5
    stop_grace_period: 60s
    environment:
      - 'TZ=Europe/Berlin'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - "${HOME}/homeassistant:/config:rw"
      - 'storage:/config/.storage:rw'
      - "${HOME}/homeassistant/www:/media:rw"
    networks:
      - backend
    ports:
      - '0.0.0.0:8123:8123/tcp'
      - '0.0.0.0:8943:8943/tcp'
    depends_on:
      - mariadb

  mariadb:
    container_name: hass-db
    image: 'mariadb:lts'
    restart: unless-stopped
    init: true
    privileged: false
    healthcheck:
      test: [ "CMD", "echo", "\"", "mysqladmin", "ping", "--wait=5", "--connect-timeout=5", "--host=localhost", "--user=root", "--password=$${MARIADB_ROOT_PASSWORD}", "\"" ]
      start_period: 10s
      interval: 15s
      timeout: 5s
      retries: 5
    stop_grace_period: 60s
    environment:
      - 'TZ=Europe/Berlin'
      - 'MARIADB_ROOT_PASSWORD=qwertz#2022'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - 'db-data:/var/lib/mysql:rw'
      - "${HOME}/homeassistant/sql:/docker-entrypoint-initdb.d:ro"
    networks:
      - backend

volumes:
  storage:
    driver: local
  db-data:
    driver: local

networks:
  backend:
    name: hass-backend
    driver: bridge

...
