---

services:
  homeassistant:
    container_name: hass02
    image: "ghcr.io/home-assistant/home-assistant:stable"
    privileged: false
    user: 1000:1000
    restart: unless-stopped
    # command: [ "python", "-m", "homeassistant", "--config", "/config", "--log-rotate-days", '3' ]
    environment:
      - TZ='Europe/Berlin'
    volumes:
      - /home/northdakota/homeassistant02:/config:rw
      - /home/northdakota/homeassistant02/www:/media:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      backend:
        ipv4_address: 172.20.0.2
    ports:
      - 8123:8123
      - 8943:8943
    depends_on:
      - mariadb

  mariadb:
    container_name: hass02-db
    image: "mariadb:10.9.4"
    privileged: false
    user: 1000:1000
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=qwertz
      - TZ='Europe/Berlin'
    volumes:
      - /home/northdakota/homeassistant02_db:/var/lib/mysql
      - /home/northdakota/homeassistant02/sql:/docker-entrypoint-initdb.d
    networks:
      backend:
        ipv4_address: 172.20.0.3

  test:
    container_name: hass02-test
    image: "rockylinux:9"
    tty: true
    networks:
      backend:
        ipv4_address: 172.20.0.4


  # nodered:
  #   container_name: homeassistant02_nodered
  #   image: "nodered/node-red:latest-minimal"
  #   privileged: false
  #   user: 1000:1000
  #   restart: unless-stopped
  #   environment:
  #     - TZ='Europe/Berlin'
  #   volumes:
  #     - <local data path>:/data
  #     - /etc/localtime:/etc/localtime:ro
  #     - /etc/timezone:/etc/timezone:ro
  #   networks:
  #     - backend
  #   ports:
  #     - "1880:1880"

networks:
  backend:
    name: hass02-backend
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/29
          gateway: 172.20.0.1

...

