---

services:
  searxng:
    container_name: searxng
    image: 'searxng/searxng:latest'
    init: true
    privileged: false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--timeout=5", "--spider", "--no-check-certificate", "--quiet", "http://127.0.0.1:8080/info/en/about"]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      - 'TZ=Europe/Berlin'
      - 'SEARXNG_BASE_URL=http://dockerhost01.prd.florian-hild.de/'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - './searxng:/etc/searxng:rw'
    networks:
      - frontend
      - backend
    ports:
      - '0.0.0.0:8050:8080/tcp'
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    depends_on:
      - redis

  redis:
    container_name: searxng_redis
    image: 'redis:alpine'
    init: true
    privileged: false
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 15s
      timeout: 5s
      retries: 5
    stop_grace_period: 60s
    command: redis-server --save "" --appendonly "no"
    environment:
      - 'TZ=Europe/Berlin'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
    tmpfs:
      - '/var/lib/redis'
    networks:
      - backend
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

networks:
  frontend:
    name: searxng-frontend
    driver: bridge
  backend:
    name: searxng-backend
    driver: bridge

...
